### ISSUE TITLE
 examples :)

### ISSUE THREAD

**Issue by ORESoftware** [hgourvest/glpk.js#2]
Hi there - nice work with this library

Could you put up some examples on how to use GLPK.js?

I personally am interested in using it for MIP - can this library work with mixed-integer programming?

I heard GLPK wasn't very reliable for MIP. But I have a node.js app, so talking with a JS library is the easiest way to get started. 

thanks !!

**Comment by hgourvest** [comment]
Yes it work for MIP, but I have not translated any sample from GLPK.
It is the same API than GLPK, so it is quite easy to translate GLPK samples.

If it can help you, AFAIK, there is 2 online IDE that use glpk.js:
http://www3.nd.edu/~jeff/mathprog/mathprog.html
http://online-optimizer.appspot.com/
source code: https://github.com/yozw/lio-ng

In my own opinion GLPK is the best open source library to solve MIP problems.
glpk.js can work either in a browser and with nodejs,
but I only use nodejs for debuging purpose.
It is not a good idea to use it on the server side,
or you should find a binding for the native library.

regards

**Comment by ORESoftware** [comment]
Henri have you used COIN-OR CBC?

**Comment by hgourvest** [comment]
no, I have not translated this API part.

**Comment by ORESoftware** [comment]
ok thx
